workflows:
  ermokids_android_build:
    name: ErmoKids Android Build
    max_build_duration: 60

    environment:
      node: latest
      java: 21

    scripts:
      - name: Check versions
        script: |
          node -v
          java -version

      - name: Install dependencies
        script: |
          npm install

      - name: Install Capacitor CLI
        script: |
          npm install -D @capacitor/cli@latest

      - name: Build web
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk


