workflows:
  android-workflow:
    name: ErmoKids Android Build
    max_build_duration: 60
    instance_type: linux
    environment:
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
