workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.ermotech.ermokids"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - hclinformatica2025@gmail.com
